# Prueba de evaluación 1 - Parte 3
- Entornos de data science con Python
- Curso 2015/16.
***
- Autor: Juan Antonio García Cuevas
- Fecha: 14/07/2016
***

# Parte 3
Podemos descargar datos de empresas del dataset Forbes2000 (paquete HSAUR) mediante get_rdataset(). Encontraremos un ranking de empresas categorizadas por sector, y con datos de su país, ventas, beneficios, recursos y valor de mercado.

- Seleccionar del dataframe los nombres de empresa que incluyen "elect" (sin tener en cuenta mayúsculas). Intentamos con esto obtener empresas “del sector de la electricidad” de forma aproximada.
- Utilizando como índice el país y la categoría y ordenándolo (sort_index), encontrar el valor de mercado de las empresas japonesas y estadounidenses.
- Sobre el mismo subconjunto de empresas eléctricas, obtener el país donde el sector de utilities tiene mayor valor de mercado medio en sus empresas.
- Volviendo al dataset original, obtener las empresas españolas.
- Indexar el dataframe anterior por beneficios (profits) y obtener los nombres y rangos de las que tengan un beneficio nulo o negativo. Nota: intenta indexar de manera mixta con números (filas) y etiquetas columnas), hay una operación específica para esto en pandas.

In [1]:
%matplotlib inline

### Cargar datos de empresas

In [2]:
import statsmodels.api as sm

rforbes = sm.datasets.get_rdataset('Forbes2000', 'HSAUR')

data = rforbes.data
numrows_data, numcols_data = data.shape
print 'Número de filas...:', numrows_data
print 'Número de columnas:', numcols_data
data.head()

Número de filas...: 2000
Número de columnas: 8

,rank,name,country,category,sales,profits,assets,marketvalue
0,1,Citigroup,United States,Banking,94.71,17.85,1264.03,255.30
1,2,General Electric,United States,Conglomerates,134.19,15.59,626.93,328.54
2,3,American Intl Group,United States,Insurance,76.66,6.46,647.66,194.87
3,4,ExxonMobil,United States,Oil & gas operations,222.88,20.96,166.99,277.02
4,5,BP,United Kingdom,Oil & gas operations,232.57,10.27,177.57,173.54

### Seleccionar del dataframe los nombres de empresa que incluyen "elect" (sin tener en cuenta mayúsculas). Intentamos con esto obtener empresas “del sector de la electricidad” de forma aproximada.

In [3]:
subdata = data[data.name.str.contains("elect", case = False)]
numrows_subdata, numcols_subdata = subdata.shape
print 'Número de filas...:', numrows_subdata
print 'Número de columnas:', numcols_subdata
subdata.head()

Número de filas...: 50
Número de columnas: 8

,rank,name,country,category,sales,profits,assets,marketvalue
1,2,General Electric,United States,Conglomerates,134.19,15.59,626.93,328.54
44,45,Samsung Electronics,South Korea,Semiconductors,50.22,5.95,54.58,72.72
71,72,Tokyo Electric Power,Japan,Utilities,41.62,1.40,116.68,30.63
151,152,Korea Electric Power,South Korea,Utilities,18.01,2.57,58.38,11.84
156,157,Kansai Electric Power,Japan,Utilities,22.12,0.68,60.52,17.56

### Utilizando como índice el país y la categoría y ordenándolo (sort_index), encontrar el valor de mercado de las empresas japonesas y estadounidenses.

In [4]:
subdataindexed = subdata.set_index(['country', 'category'])
subdataindexed.sort_index(inplace=True)
numrows_subdataindexed, numcols_subdataindexed = subdataindexed.shape
print 'Número de filas...:', numrows_subdataindexed
print 'Número de columnas:', numcols_subdataindexed
subdataindexed

Número de filas...: 50
Número de columnas: 6

                                                  rank  \
country         category
Austria         Utilities                         1184
China           Utilities                         1842
France          Capital goods                      323
Hong Kong/China Capital goods                     1582
                Utilities                          811
Japan           Business services & supplies      1333
                Business services & supplies      1461
                Business services & supplies      1468
                Business services & supplies      1997
                Capital goods                      586
                Capital goods                      635
                Capital goods                      787
                Capital goods                     1251
                Capital goods                     1395
                Consumer durables                  415
                Consumer durables                  642
                Consumer durables                 1337
                Consumer durables                 1989
                Semiconductors                    1156
                Technology hardware & equipment   1968
                Transportation                    1079
                Transportation                    1274
                Transportation                    1581
                Utilities                           72
                Utilities                          157
                Utilities                          171
                Utilities                          281
                Utilities                          285
                Utilities                          440
                Utilities                          728
                Utilities                          799
                Utilities                          857
South Korea     Semiconductors                      45
                Technology hardware & equipment   1463
                Utilities                          152
Sweden          Consumer durables                  434
Switzerland     Semiconductors                     425
Taiwan          Semiconductors                     830
                Technology hardware & equipment   1199
                Technology hardware & equipment   1821
United Kingdom  Retailing                         1297
United States   Conglomerates                        2
                Conglomerates                      220
                Health care equipment & services  1396
                Media                              622
                Software & services                647
                Software & services                864
                Technology hardware & equipment   1347
                Utilities                          568
                Utilities                         1836

                                                                       name  \
country         category
Austria         Utilities                         Verbund-Austrian Electric
China           Utilities                          Guangdong Electric Power
France          Capital goods                            Schneider Electric
Hong Kong/China Capital goods                     Johnson Electric Holdings
                Utilities                                 Hongkong Electric
Japan           Business services & supplies                  Alps Electric
                Business services & supplies          Nippon Electric Glass
                Business services & supplies          Oki Electric Industry
                Business services & supplies              Yokogawa Electric
                Capital goods                           Mitsubishi Electric
                Capital goods                     Matsushita Electric Works
                Capital goods                             Sumitomo Electric
                Capital goods                             Furukawa Electric
                Capital goods                                 Fuji Electric
                Consumer durables                  Matsushita Electric Indl
                Consumer durables                            Sanyo Electric
                Consumer durables                            Funai Electric
                Consumer durables                          Stanley Electric
                Semiconductors                               Tokyo Electron
                Technology hardware & equipment             Hirose Electric
                Transportation                      Odakyu Electric Railway
                Transportation                        Keio Electric Railway
                Transportation                      Keihin Electric Express
                Utilities                              Tokyo Electric Power
                Utilities                             Kansai Electric Power
                Utilities                              Chubu Electric Power
                Utilities                             Tohoku Electric Power
                Utilities                             Kyushu Electric Power
                Utilities                            Chugoku Electric Power
                Utilities                            Shikoku Electric Power
                Utilities                           Hokkaido Electric Power
                Utilities                           Hokuriku Electric Power
South Korea     Semiconductors                          Samsung Electronics
                Technology hardware & equipment         SEM-Samsung Electro
                Utilities                              Korea Electric Power
Sweden          Consumer durables                          Electrolux Group
Switzerland     Semiconductors                           STMicroelectronics
Taiwan          Semiconductors                      United Microelectronics
                Technology hardware & equipment          Compal Electronics
                Technology hardware & equipment     Chi Mei Optoelectronics
United Kingdom  Retailing                                  Kesa Electricals
United States   Conglomerates                              General Electric
                Conglomerates                              Emerson Electric
                Health care equipment & services            Thermo Electron
                Media                                    Hughes Electronics
                Software & services                     Electronic Data Sys
                Software & services                         Electronic Arts
                Technology hardware & equipment           Arrow Electronics
                Utilities                                 American Electric
                Utilities                                 Hawaiian Electric

                                                   sales  profits  assets  \
country         category
Austria         Utilities                           2.18     0.16    7.27
China           Utilities                           0.67     0.14    1.43
France          Capital goods                      11.04     0.54   14.37
Hong Kong/China Capital goods                       0.96     0.15    0.85
                Utilities                           1.49     0.88    7.26
Japan           Business services & supplies        5.09     0.15    4.00
                Business services & supplies        2.78     0.12    4.15
                Business services & supplies        4.95    -0.06    5.05
                Business services & supplies        2.78    -0.22    2.96
                Capital goods                      30.79    -0.10   26.24
                Capital goods                      11.26     0.19    9.37
                Capital goods                      12.60    -0.17   13.46
                Capital goods                       6.01    -0.96    9.91
                Capital goods                       7.04     0.03    7.73
                Consumer durables                  62.62    -0.16   60.46
                Consumer durables                  19.24    -0.62   21.65
                Consumer durables                   2.80     0.16    1.60
                Consumer durables                   2.00     0.11    1.82
                Semiconductors                      3.90    -0.35    4.36
                Technology hardware & equipment     0.57     0.10    1.63
                Transportation                      5.47     0.07   10.69
                Transportation                      3.55     0.13    4.40
                Transportation                      2.65     0.07    6.11
                Utilities                          41.62     1.40  116.68
                Utilities                          22.12     0.68   60.52
                Utilities                          18.41     0.90   52.08
                Utilities                          13.48     0.52   34.49
                Utilities                          12.02     0.54   34.69
                Utilities                           8.54     0.37   23.36
                Utilities                           4.95     0.22   11.96
                Utilities                           4.39     0.22   11.85
                Utilities                           4.08     0.18   13.09
South Korea     Semiconductors                     50.22     5.95   54.58
                Technology hardware & equipment     3.29     0.18    3.00
                Utilities                          18.01     2.57   58.38
Sweden          Consumer durables                  15.34     0.59    9.50
Switzerland     Semiconductors                      7.98     0.28   11.98
Taiwan          Semiconductors                      2.18     0.20    9.29
                Technology hardware & equipment     3.38     0.23    2.72
                Technology hardware & equipment     1.72     0.13    2.62
United Kingdom  Retailing                           5.64     0.16    2.81
United States   Conglomerates                     134.19    15.59  626.93
                Conglomerates                      14.33     1.12   15.71
                Health care equipment & services    2.10     0.20    3.39
                Media                              10.12    -0.30   18.95
                Software & services                21.48    -0.27   18.28
                Software & services                 2.82     0.50    3.34
                Technology hardware & equipment     8.09     0.01    5.04
                Utilities                          15.58    -0.16   36.08
                Utilities                           1.76     0.10    9.03

                                                  marketvalue
country         category
Austria         Utilities                                4.28
China           Utilities                                3.39
France          Capital goods                           15.39
Hong Kong/China Capital goods                            4.73
                Utilities                                9.04
Japan           Business services & supplies             2.30
                Business services & supplies             3.25
                Business services & supplies             2.69
                Business services & supplies             3.29
                Capital goods                           10.28
                Capital goods                            6.54
                Capital goods                            6.38
                Capital goods                            2.52
                Capital goods                            1.55
                Consumer durables                       33.02
                Consumer durables                        9.43
                Consumer durables                        4.70
                Consumer durables                        3.23
                Semiconductors                          11.71
                Technology hardware & equipment          4.29
                Transportation                           3.72
                Transportation                           3.49
                Transportation                           3.22
                Utilities                               30.63
                Utilities                               17.56
                Utilities                               15.59
                Utilities                                8.67
                Utilities                                8.48
                Utilities                                6.41
                Utilities                                4.65
                Utilities                                3.76
                Utilities                                3.74
South Korea     Semiconductors                          72.72
                Technology hardware & equipment          2.74
                Utilities                               11.84
Sweden          Consumer durables                        6.93
Switzerland     Semiconductors                          24.11
Taiwan          Semiconductors                          14.66
                Technology hardware & equipment          4.07
                Technology hardware & equipment          3.68
United Kingdom  Retailing                                2.72
United States   Conglomerates                          328.54
                Conglomerates                           26.88
                Health care equipment & services         4.63
                Media                                   23.56
                Software & services                      9.98
                Software & services                     13.28
                Technology hardware & equipment          2.67
                Utilities                               13.21
                Utilities                                1.94

In [5]:
def marketValueByCountry(countrylist):
    fieldlist = ['name', 'marketvalue']
    return subdataindexed[[country in countrylist for country,category in subdataindexed.index ]][fieldlist]

countrylist = ['Japan', 'United States']
marketValueByCountry(countrylist)

                                                                     name  \
country       category
Japan         Business services & supplies                  Alps Electric
              Business services & supplies          Nippon Electric Glass
              Business services & supplies          Oki Electric Industry
              Business services & supplies              Yokogawa Electric
              Capital goods                           Mitsubishi Electric
              Capital goods                     Matsushita Electric Works
              Capital goods                             Sumitomo Electric
              Capital goods                             Furukawa Electric
              Capital goods                                 Fuji Electric
              Consumer durables                  Matsushita Electric Indl
              Consumer durables                            Sanyo Electric
              Consumer durables                            Funai Electric
              Consumer durables                          Stanley Electric
              Semiconductors                               Tokyo Electron
              Technology hardware & equipment             Hirose Electric
              Transportation                      Odakyu Electric Railway
              Transportation                        Keio Electric Railway
              Transportation                      Keihin Electric Express
              Utilities                              Tokyo Electric Power
              Utilities                             Kansai Electric Power
              Utilities                              Chubu Electric Power
              Utilities                             Tohoku Electric Power
              Utilities                             Kyushu Electric Power
              Utilities                            Chugoku Electric Power
              Utilities                            Shikoku Electric Power
              Utilities                           Hokkaido Electric Power
              Utilities                           Hokuriku Electric Power
United States Conglomerates                              General Electric
              Conglomerates                              Emerson Electric
              Health care equipment & services            Thermo Electron
              Media                                    Hughes Electronics
              Software & services                     Electronic Data Sys
              Software & services                         Electronic Arts
              Technology hardware & equipment           Arrow Electronics
              Utilities                                 American Electric
              Utilities                                 Hawaiian Electric

                                                marketvalue
country       category
Japan         Business services & supplies             2.30
              Business services & supplies             3.25
              Business services & supplies             2.69
              Business services & supplies             3.29
              Capital goods                           10.28
              Capital goods                            6.54
              Capital goods                            6.38
              Capital goods                            2.52
              Capital goods                            1.55
              Consumer durables                       33.02
              Consumer durables                        9.43
              Consumer durables                        4.70
              Consumer durables                        3.23
              Semiconductors                          11.71
              Technology hardware & equipment          4.29
              Transportation                           3.72
              Transportation                           3.49
              Transportation                           3.22
              Utilities                               30.63
              Utilities                               17.56
              Utilities                               15.59
              Utilities                                8.67
              Utilities                                8.48
              Utilities                                6.41
              Utilities                                4.65
              Utilities                                3.76
              Utilities                                3.74
United States Conglomerates                          328.54
              Conglomerates                           26.88
              Health care equipment & services         4.63
              Media                                   23.56
              Software & services                      9.98
              Software & services                     13.28
              Technology hardware & equipment          2.67
              Utilities                               13.21
              Utilities                                1.94

### Sobre el mismo subconjunto de empresas eléctricas, obtener el país donde el sector de utilities tiene mayor valor de mercado medio en sus empresas.

In [6]:
utilities = subdataindexed[[category == 'Utilities' for country, category in subdataindexed.index]]
marketvalue_countries  = utilities.groupby(level = 0).mean()[['marketvalue']]
marketvalue_countries.sort_values(by='marketvalue', ascending=False)

                 marketvalue
country
South Korea        11.840000
Japan              11.054444
Hong Kong/China     9.040000
United States       7.575000
Austria             4.280000
China               3.390000

### Volviendo al dataset original, obtener las empresas españolas.

In [7]:
data[data.country == 'Spain'].sort_values(by='name')

,rank,name,country,category,sales,profits,assets,marketvalue
876,877,ACS Group,Spain,Construction,4.64,0.19,5.16,6.24
1059,1060,Abertis Infraestructuras,Spain,Transportation,0.80,0.21,6.78,7.43
1035,1036,Acciona,Spain,Construction,3.59,0.17,6.11,4.13
1493,1494,Acerinox,Spain,Materials,2.63,0.18,2.70,3.05
472,473,Altadis,Spain,Food drink & tobacco,9.45,0.46,8.66,9.48
1426,1427,Amadeus Global Travel,Spain,Business services & supplies,2.43,0.20,1.34,3.60
56,57,BBVA-Banco Bilbao Vizcaya,Spain,Banking,24.10,2.81,288.80,44.67
1892,1893,Banco Pastor,Spain,Banking,0.49,0.08,13.12,1.79
378,379,Banco Popular Espaqol,Spain,Banking,3.32,0.67,44.01,14.38
38,39,Banco Santander Central,Spain,Banking,28.70,3.28,442.24,56.78
787,788,Banco de Sabadell,Spain,Banking,1.99,0.30,38.38,4.77
1058,1059,Bankinter,Spain,Banking,1.37,0.17,30.05,3.26
532,533,Cepsa,Spain,Oil & gas operations,8.85,0.48,6.31,9.29
951,952,Corporation Mapfre,Spain,Insurance,5.87,0.12,15.45,2.73
1623,1624,Enagas,Spain,Oil & gas operations,1.97,0.18,3.89,2.83
114,115,Endesa Group,Spain,Utilities,20.43,1.65,57.92,21.10
734,735,FCC Group,Spain,Construction,5.77,0.29,7.14,4.99
1931,1932,Gamesa,Spain,Capital goods,1.15,0.14,2.04,3.02
462,463,Gas Natural SDG,Spain,Utilities,5.53,0.85,9.25,11.28
605,606,Grupo Ferrovial,Spain,Construction,5.29,0.48,11.78,5.11
188,189,Iberdrola,Spain,Utilities,11.94,1.33,30.99,18.78
1074,1075,Iberia,Spain,Transportation,4.71,0.17,4.85,3.34
762,763,Inditex,Spain,Household & personal products,4.28,0.47,3.24,13.52
1897,1898,Red Eectrica de Espaqa,Spain,Utilities,1.14,0.15,4.28,2.36
108,109,Repsol-YPF,Spain,Oil & gas operations,29.14,2.05,39.34,26.22
1435,1436,Sacyr-Vallehermoso,Spain,Diversified financials,0.88,0.22,3.75,4.09
1992,1993,Sogecable,Spain,Media,1.03,-0.06,1.53,6.02
408,409,Telefsnica,Spain,Telecommunications services,29.84,-5.86,60.65,86.39
529,530,Unisn Fenosa,Spain,Utilities,6.13,0.36,15.71,6.35

### Indexar el dataframe anterior por beneficios (profits) y obtener los nombres y rangos de las que tengan un beneficio nulo o negativo. Nota: intenta indexar de manera mixta con números (filas) y etiquetas columnas), hay una operación específica para esto en pandas.

In [8]:
subdata = data[data.country == 'Spain']
subdataindexed = subdata.set_index('profits')
subdataindexed.sort_index(inplace=True)
subdataindexed.ix[:0, ['name', 'rank']]

               name  rank
profits
-5.86    Telefsnica   409
-0.06     Sogecable  1993